sudo: required

services:
  - docker

language:
  - cpp

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudev-dev valgrind
  - git clone https://github.com/OpenZWave/open-zwave.git
  - sudo make -C open-zwave install
  - git clone https://github.com/eclipse/mosquitto.git
  - make -C mosquitto WITH_SRV=no WITH_UUID=no WITH_DOCS=no
  - sudo make -C mosquitto WITH_DOCS=no install
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xzf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake .
  - sudo make install
  - cd ..

jobs:
  include:
    - &test
      stage: Tests
      compiler: gcc
      script:
        - cmake .
        - make all test
    - <<: *test
      compiler: clang

    - &stage
      stage: Dockers
      env:
        - BASE=ubuntu
        - TAG=latest
      install: skip
      script: &dock
        - cd docker
        - ./build_docker
    - <<: *stage
      env:
        - BASE=resin/odroid-xu4-debian
        - TAG=odroid-xu4
