sudo: required
language:
  - cpp
compiler:
  -gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmosquitto0-dev libudev-dev

install:
  - git clone https://github.com/OpenZWave/open-zwave.git
  - sudo make -C open-zwave install
  - git clone https://github.com/eclipse/mosquitto.git
  - sudo make -C mosquitto WITH_SRV=no WITH_UUID=no WITH_DOCS=no install

script:
  - mkdir -p build
  - cd build
  - cmake ../
  - make
  - make test
